### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'incomplete_dates_for_task_chapter'

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#166]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/89/](https://rollbar.com/frank.ventura/CMT/items/89/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/braces/views/_access.py", line 351, in dispatch
    request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/testCMT/core/views.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 189, in get
    self.object = self.get_object()
  File "/home/Venturafranklin/testCMT/thetatauCMT/forms/views.py", line 842, in get_object
    next_date = task.incomplete_dates_for_task_chapter(chapter).first()
AttributeError: 'NoneType' object has no attribute 'incomplete_dates_for_task_chapter'
```

**Comment by VenturaFranklin** [comment]
Fixed by b07e2cbff5d43a6e1108e552fbc109a52e4902b4
