### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#185]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/111/](https://rollbar.com/frank.ventura/CMT/items/111/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/braces/views/_access.py", line 351, in dispatch
    request, *args, **kwargs)
  File "/home/Venturafranklin/thetatauCMT/core/views.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/Venturafranklin/thetatauCMT/core/views.py", line 103, in form_valid
    response = super().form_valid(form)  # This saves the form
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/forms/models.py", line 458, in save
    self.instance.save()
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/submissions/models.py", line 41, in save
    cal_score = self.type.calculate_score(self, extra_info=extra_info)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/scores/models.py", line 179, in calculate_score
    return self.calculate_special(obj, extra_info=extra_info)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/scores/models.py", line 165, in calculate_special
    unmodified = extra_info.get('unmodified', False)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by VenturaFranklin** [comment]
Closed by df95518b738a0ec5dc6b4bf9a1327926f86b614f
