### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "tasks_task_slug_key"
DETAIL:  Key (slug)=(new-jersey-institute-of-technolony-petitionregent) already exists.


### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#208]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/120/](https://rollbar.com/frank.ventura/CMT/items/120/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1637, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1088, in save_model
    obj.save()
  File "/home/Venturafranklin/testCMT/thetatauCMT/ballots/models.py", line 85, in save
    new_task.save()
  File "/home/Venturafranklin/testCMT/thetatauCMT/tasks/models.py", line 45, in save
    super().save(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "tasks_task_slug_key"
DETAIL:  Key (slug)=(new-jersey-institute-of-technolony-petitionregent) already exists.
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
UniqueViolation: duplicate key value violates unique constraint "tasks_task_slug_key"
DETAIL:  Key (slug)=(new-jersey-institute-of-technolony-petitionregent) already exists.

```

**Comment by VenturaFranklin** [comment]
Fixed by d224ae01da8e5e9f4aacea613a80421b83bd14c9
