### ISSUE TITLE
AttributeError: 'Ballot' object has no attribute 'ballot_type'

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#209]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/121/](https://rollbar.com/frank.ventura/CMT/items/121/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1637, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1561, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1088, in save_model
    obj.save()
  File "/home/Venturafranklin/testCMT/thetatauCMT/ballots/models.py", line 92, in save
    super().save()
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/base.py", line 848, in _save_table
    for f in non_pks]
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/base.py", line 848, in <listcomp>
    for f in non_pks]
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 288, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 86, in save
    name = self.field.generate_filename(self.instance, name)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 303, in generate_filename
    filename = self.upload_to(instance, filename)
  File "/home/Venturafranklin/testCMT/thetatauCMT/ballots/models.py", line 15, in get_ballot_attachment_upload_path
    'ballots', instance.ballot_type,
AttributeError: 'Ballot' object has no attribute 'ballot_type'
```

**Comment by VenturaFranklin** [comment]
Fixed by 5470dfce84ae17b5f6090bddca8c0010edd0087c
