### ISSUE TITLE
AttributeError: 'RoleChangeNationalView' object has no attribute 'object_list'

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#210]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/122/](https://rollbar.com/frank.ventura/CMT/items/122/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/braces/views/_access.py", line 351, in dispatch
    request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/testCMT/core/views.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/testCMT/thetatauCMT/forms/views.py", line 564, in post
    return self.formset_invalid(formset)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/extra_views/formsets.py", line 142, in formset_invalid
    return self.render_to_response(self.get_context_data(formset=formset))
  File "/home/Venturafranklin/testCMT/thetatauCMT/forms/views.py", line 571, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/home/Venturafranklin/.virtualenvs/testCMT/local/lib/python3.6/site-packages/django/views/generic/list.py", line 115, in get_context_data
    queryset = object_list if object_list is not None else self.object_list
AttributeError: 'RoleChangeNationalView' object has no attribute 'object_list'
```

**Comment by VenturaFranklin** [comment]
Fixed by d4f0cb0844e7f56d34ce2c0932c9ee4de6a1218b
