### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "users_user_username_key"
DETAIL:  Key (username)=(dawnn.2015@gmail.com) already exists.


### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#225]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/135/](https://rollbar.com/frank.ventura/CMT/items/135/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/thetatauCMT/core/views.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/thetatauCMT/core/forms.py", line 92, in post
    return self._process_individual_form(form_name, form_classes)
  File "/home/Venturafranklin/thetatauCMT/core/forms.py", line 110, in _process_individual_form
    return self.forms_valid(forms, form_name)
  File "/home/Venturafranklin/thetatauCMT/core/forms.py", line 43, in forms_valid
    return getattr(self, form_valid_method)(forms[form_name])
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/chapters/views.py", line 36, in faculty_form_valid
    user = form.save()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/forms/models.py", line 458, in save
    self.instance.save()
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/users/models.py", line 58, in save
    super(User, self).save(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "users_user_username_key"
DETAIL:  Key (username)=(dawnn.2015@gmail.com) already exists.
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
UniqueViolation: duplicate key value violates unique constraint "users_user_username_key"
DETAIL:  Key (username)=(dawnn.2015@gmail.com) already exists.

```

**Comment by VenturaFranklin** [comment]
Need a note that the Faculty form in the report and on the Chapter page is only for EXTERNAL people not alumni.

**Comment by VenturaFranklin** [comment]
Can handle alumni of the chapter, but what about alumni from another chapter?
```       
 if formset.has_changed():
            for form in formset.forms:
                if form.changed_data and 'DELETE' not in form.changed_data:
                    chapter = self.request.user.current_chapter
                    if form.instance.badge_number == 999999999:
                        form.instance.chapter = chapter
                        form.instance.badge_number = chapter.next_advisor_number
                    try:
                        # This is either a previous faculty or alumni
                        user = User.objects.get(username=form.instance.email)
                    except User.DoesNotExist:
                        user = form.save()
                    if user.badge_number >= 7000:
                        # This is external advisor
                        try:
                            # Need to check if previous
                            status = UserStatusChange.objects.get(
                                user=user, status='advisor')
                        except UserStatusChange.DoesNotExist:
                            UserStatusChange(
                                user=user,
                                status='advisor',
                                start=TODAY_START,
                                end=forever(),
                            ).save()
                            EmailAdvisorWelcome(user).send()
                        else:
                            status.end = forever()
                            status.save()
                    else:
                        # This is an alumni
                        try:
                            # Need to check if previous
                            status = UserRoleChange.objects.get(
                                user=user, status='faculty adviser')
                        except UserRoleChange.DoesNotExist:
                            UserRoleChange(
                                user=user,
                                role='faculty adviser',
                                start=TODAY_START,
                                end=forever(),
                            ).save()
                            EmailAdvisorWelcome(user).send()
                        else:
                            status.end = forever()
                            status.save()
```
