### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not NoneType

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#254]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/156/](https://rollbar.com/frank.ventura/CMT/items/156/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/braces/views/_access.py", line 351, in dispatch
    request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/thetatauCMT/core/views.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/regions/views.py", line 125, in get
    if row[2] in emails:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

**Comment by VenturaFranklin** [comment]
Closed by 7608f1a40231e8f0cd36fae34d159e30c6bcb0f9
