### ISSUE TITLE
Disable LinkedIn

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#59]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/10/](https://rollbar.com/frank.ventura/CMT/items/10/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 134, in dispatch
    response=access_token)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/allauth/socialaccount/providers/linkedin_oauth2/views.py", line 24, in complete_login
    request, extra_data)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/allauth/socialaccount/providers/base.py", line 86, in sociallogin_from_response
    uid = self.extract_uid(response)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/allauth/socialaccount/providers/linkedin_oauth2/provider.py", line 37, in extract_uid
    return str(data['id'])
KeyError: 'id'
```

**Comment by VenturaFranklin** [comment]
Until we can update allauth (which requires Django 1.1) we can not use LinkedIn because of the API change
