### ISSUE TITLE
TypeError: Tried to update field users.User.current_status with a model instance, <UserStatusChange: alumnipend>. Use a value compatible with CharField.

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#925]
View details in Rollbar: [https://app.rollbar.com/a/frank.ventura/fix/item/CMT/560](https://app.rollbar.com/a/frank.ventura/fix/item/CMT/560)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/decorators.py", line 213, in _wrapper
    return view(request, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/flow/views/task.py", line 74, in dispatch
    return super(BaseFlowMixin, self).dispatch(request, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/flow/views/task.py", line 90, in form_valid
    self.activation_done(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/flow/views/task.py", line 82, in activation_done
    self.activation.done()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 44, in __call__
    return self.descriptor(self.instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 112, in __call__
    result = self.func(instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/activation.py", line 387, in done
    self.activate_next()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 44, in __call__
    return self.descriptor(self.instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 112, in __call__
    result = self.func(instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/activation.py", line 399, in activate_next
    self.flow_task._next.activate(prev_activation=self, token=self.task.token)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/__init__.py", line 154, in activate
    return self.activation_class.activate(self, prev_activation, token)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/activation.py", line 566, in activate
    activation.perform()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 44, in __call__
    return self.descriptor(self.instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 112, in __call__
    result = self.func(instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/activation.py", line 530, in perform
    self.activate_next()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 44, in __call__
    return self.descriptor(self.instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 169, in __call__
    result = self.func(instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/nodes/ifgate.py", line 24, in activate_next
    self.flow_task._on_false.activate(prev_activation=self, token=self.task.token)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/__init__.py", line 154, in activate
    return self.activation_class.activate(self, prev_activation, token)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/nodes/handler.py", line 65, in activate
    activation.perform()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 44, in __call__
    return self.descriptor(self.instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/fsm.py", line 112, in __call__
    result = self.func(instance, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/nodes/handler.py", line 26, in perform
    self.execute()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/viewflow/nodes/handler.py", line 16, in execute
    self.flow_task.handler(self)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/forms/flows.py", line 1264, in email_complete_func
    user.reset_status()
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/users/models.py", line 263, in reset_status
    self.set_current_status(previous_status)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/users/models.py", line 295, in set_current_status
    UserStatusChange(
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/users/models.py", line 625, in save
    self.user.save(update_fields=["current_status"])
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/users/models.py", line 224, in save
    super(User, self).save(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-package

**Comment by jimgaffneyTT** [comment]
This member went pre-alum after this (old) resignation was filed.  I can't cancel the process so I was trying to just deny it.
