### ISSUE TITLE
NameError: name 'current_role' is not defined

### ISSUE THREAD

**Issue by VenturaFranklin** [VenturaFranklin/thetatauCMT#93]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/49/](https://rollbar.com/frank.ventura/CMT/items/49/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/braces/views/_access.py", line 351, in dispatch
    request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "./core/views.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/forms/views.py", line 601, in post
    return self.form_valid(form)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/forms/views.py", line 627, in form_valid
    f"You successfully submitted the Audit Form!\n"
NameError: name 'current_role' is not defined
```

**Comment by VenturaFranklin** [comment]
Closed by 15bfccbc4985e0fce582f5bf242c04f9db0a8a8b
